# Generated by codegen/generate.py from mawaqit/api-spec v0.5.1. Do not edit.
"""The resources of the clients: one group of operations per tag of the API."""

from .auth import AsyncAuth, Auth
from .hadiths import AsyncHadiths, Hadiths
from .mosques import AsyncMosques, Mosques

__all__ = [
    "AsyncAuth",
    "AsyncHadiths",
    "AsyncMosques",
    "Auth",
    "Hadiths",
    "Mosques",
]
