# Generated by codegen/generate.py from mawaqit/api-spec v0.3.0. Do not edit.
"""The resources of the clients: one group of operations per tag of the API."""

from .auth import AsyncAuth, Auth
from .mosques import AsyncMosques, Mosques

__all__ = [
    "AsyncAuth",
    "AsyncMosques",
    "Auth",
    "Mosques",
]
