# Generated by codegen/generate.py from mawaqit/api-spec v0.4.0. Do not edit.
"""Get an API token."""

from __future__ import annotations

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource
from ..types import Account

__all__ = ["AsyncAuth", "Auth"]

_LOGIN = TypeAdapter[Account](Account)


class AsyncAuth(AsyncAPIResource):
    """Get an API token."""

    async def login(self, *, email: str, password: str) -> Account:
        """Log in.

        Return the account of an email and password, with its API token.

        The token is created on the first call and stays the same afterwards, so it can
        be stored instead of the password.

        Args:
            email: Email of the MAWAQIT account.
            password: Password of the MAWAQIT account.

        Returns:
            The account.

        Raises:
            AuthenticationError: Wrong email or password.
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "POST",
            "/2.0/me",
            basic_auth=(email, password),
            authenticated=False,
            response_type=_LOGIN,
        )


class Auth(SyncAPIResource):
    """Get an API token."""

    def login(self, *, email: str, password: str) -> Account:
        """Log in.

        Return the account of an email and password, with its API token.

        The token is created on the first call and stays the same afterwards, so it can
        be stored instead of the password.

        Args:
            email: Email of the MAWAQIT account.
            password: Password of the MAWAQIT account.

        Returns:
            The account.

        Raises:
            AuthenticationError: Wrong email or password.
            APIError: The request failed in another way.
        """
        return self._client._request(
            "POST",
            "/2.0/me",
            basic_auth=(email, password),
            authenticated=False,
            response_type=_LOGIN,
        )
