# Generated by codegen/generate.py from mawaqit/api-spec v0.5.1. Do not edit.
"""Read the hadiths shown on the mosque screens."""

from __future__ import annotations

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource
from ..types import Hadith

__all__ = ["AsyncHadiths", "Hadiths"]

_RANDOM = TypeAdapter[Hadith | None](Hadith | None)


class AsyncHadiths(AsyncAPIResource):
    """Read the hadiths shown on the mosque screens."""

    async def random(
        self, *, lang: str | None = None, max_length: int | None = None
    ) -> Hadith | None:
        """Get a random hadith.

        Return a hadith drawn at random among those of a language shorter than
        `max_length`, or `None` when none is short enough.

        Responses are cached for an hour: the same parameters return the same hadith for
        up to an hour.

        Args:
            lang: Language of the hadith: `ar`, `de`, `en`, `es`, `fi`, `fr`, `nl`,
                `pt`, `ta` or `tr`. A pair with Arabic, like `fr-ar`, draws one of its
                two languages at random, like the `hadith_lang` of the mosque screens.
                Any other value gives Arabic. `ar` by default.
            max_length: The text is shorter than this many bytes of UTF-8, where an
                Arabic letter takes 2. Ignored when `lang` is `ta`: the hadith is then
                shorter than 1000 bytes. At least 1, 500 by default.

        Returns:
            The hadith, or `None` when none is short enough.

        Raises:
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/2.0/hadith/random",
            params={"lang": lang, "maxLength": max_length},
            authenticated=False,
            empty_as_none=True,
            response_type=_RANDOM,
        )


class Hadiths(SyncAPIResource):
    """Read the hadiths shown on the mosque screens."""

    def random(
        self, *, lang: str | None = None, max_length: int | None = None
    ) -> Hadith | None:
        """Get a random hadith.

        Return a hadith drawn at random among those of a language shorter than
        `max_length`, or `None` when none is short enough.

        Responses are cached for an hour: the same parameters return the same hadith for
        up to an hour.

        Args:
            lang: Language of the hadith: `ar`, `de`, `en`, `es`, `fi`, `fr`, `nl`,
                `pt`, `ta` or `tr`. A pair with Arabic, like `fr-ar`, draws one of its
                two languages at random, like the `hadith_lang` of the mosque screens.
                Any other value gives Arabic. `ar` by default.
            max_length: The text is shorter than this many bytes of UTF-8, where an
                Arabic letter takes 2. Ignored when `lang` is `ta`: the hadith is then
                shorter than 1000 bytes. At least 1, 500 by default.

        Returns:
            The hadith, or `None` when none is short enough.

        Raises:
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/2.0/hadith/random",
            params={"lang": lang, "maxLength": max_length},
            authenticated=False,
            empty_as_none=True,
            response_type=_RANDOM,
        )
