# Generated by codegen/generate.py from mawaqit/api-spec v0.3.0. Do not edit.
"""Search mosques and read their prayer times."""

from __future__ import annotations

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource
from ..types import FlashMessage, HijriSettings, Mosque, MosqueConfig, PrayerTimes

__all__ = ["AsyncMosques", "Mosques"]

_SEARCH = TypeAdapter[list[Mosque]](list[Mosque])
_PRAYER_TIMES = TypeAdapter[PrayerTimes](PrayerTimes)
_HIJRI_SETTINGS = TypeAdapter[HijriSettings](HijriSettings)
_CONFIG = TypeAdapter[MosqueConfig](MosqueConfig)
_FLASH_MESSAGE = TypeAdapter[FlashMessage | None](FlashMessage | None)


class AsyncMosques(AsyncAPIResource):
    """Search mosques and read their prayer times."""

    async def search(
        self,
        *,
        word: str | None = None,
        lat: float | None = None,
        lon: float | None = None,
        radius: int | None = None,
        page: int | None = None,
        items_per_page: int | None = None,
    ) -> list[Mosque]:
        """Search mosques.

        Search mosques by name and address, or around a position.

        A position takes precedence over `word`. Around a position, mosques come nearest
        first, and the search radius grows by 5 km up to 20 km until a mosque is found.
        Without a `word` of 2 characters or more and without a position, the result is
        empty.

        Args:
            word: Words to look for in the name and address of the mosques. Only the
                first 30 characters are used.
            lat: Latitude of the position to search around, in degrees. From -90 to 90.
            lon: Longitude of the position to search around, in degrees. From -180 to
                180.
            radius: Initial search radius around the position, in kilometers. From 1 to
                20, 5 by default.
            page: Page of results. At least 1, 1 by default.
            items_per_page: Number of mosques per page. From 1 to 50, 10 by default.

        Returns:
            The mosques found, possibly none.

        Raises:
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/2.0/mosque/search",
            params={
                "word": word,
                "lat": lat,
                "lon": lon,
                "radius": radius,
                "page": page,
                "itemsPerPage": items_per_page,
            },
            authenticated=False,
            response_type=_SEARCH,
        )

    async def prayer_times(self, uuid: str) -> PrayerTimes:
        """Get prayer times.

        Return the information, prayer times and iqama times of a mosque for the whole
        year.

        Responses are cached for a long time: `times`, `shuruq` and the Jumu'a times
        describe the day the response was generated, so read the times of a given day
        from `calendar` and `iqama_calendar` instead.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The prayer times of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/2.0/mosque/{uuid}/prayer-times",
            path_params={"uuid": uuid},
            response_type=_PRAYER_TIMES,
        )

    async def hijri_settings(self, uuid: str) -> HijriSettings:
        """Get Hijri date settings.

        Return how the Hijri date of a mosque is computed: the Kuwaiti algorithm on
        today's date shifted by `hijri_adjustment` days, with the day replaced by 30
        when `hijri_date_force_to_30` is `True`.

        These settings change around the start of the Hijri months, after the moon
        sighting, sometimes for every mosque of a country at once. Read them from this
        endpoint rather than from `client.mosques.prayer_times()`, whose copy can lag
        behind.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The Hijri date settings of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/hijri-date",
            path_params={"uuid": uuid},
            response_type=_HIJRI_SETTINGS,
        )

    async def config(self, uuid: str) -> MosqueConfig:
        """Get the screen settings.

        Return the settings of the mosque screens: what they display, the adhan and
        iqama options, and whether the mosque displays Sabah and Imsak.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The screen settings of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/config",
            path_params={"uuid": uuid},
            response_type=_CONFIG,
        )

    async def flash_message(self, uuid: str) -> FlashMessage | None:
        """Get the flash message.

        Return the flash message of a mosque, or `None` when it has none.

        The message is returned before its `start_date` and after its `end_date` too:
        the mosque screens show it from `start_date` to `end_date` included, in the time
        zone of the mosque. The same message is in the `flash` of
        `client.mosques.prayer_times()`, a much larger response.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The flash message of the mosque, or `None`.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return await self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/flash-message",
            path_params={"uuid": uuid},
            response_type=_FLASH_MESSAGE,
        )


class Mosques(SyncAPIResource):
    """Search mosques and read their prayer times."""

    def search(
        self,
        *,
        word: str | None = None,
        lat: float | None = None,
        lon: float | None = None,
        radius: int | None = None,
        page: int | None = None,
        items_per_page: int | None = None,
    ) -> list[Mosque]:
        """Search mosques.

        Search mosques by name and address, or around a position.

        A position takes precedence over `word`. Around a position, mosques come nearest
        first, and the search radius grows by 5 km up to 20 km until a mosque is found.
        Without a `word` of 2 characters or more and without a position, the result is
        empty.

        Args:
            word: Words to look for in the name and address of the mosques. Only the
                first 30 characters are used.
            lat: Latitude of the position to search around, in degrees. From -90 to 90.
            lon: Longitude of the position to search around, in degrees. From -180 to
                180.
            radius: Initial search radius around the position, in kilometers. From 1 to
                20, 5 by default.
            page: Page of results. At least 1, 1 by default.
            items_per_page: Number of mosques per page. From 1 to 50, 10 by default.

        Returns:
            The mosques found, possibly none.

        Raises:
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/2.0/mosque/search",
            params={
                "word": word,
                "lat": lat,
                "lon": lon,
                "radius": radius,
                "page": page,
                "itemsPerPage": items_per_page,
            },
            authenticated=False,
            response_type=_SEARCH,
        )

    def prayer_times(self, uuid: str) -> PrayerTimes:
        """Get prayer times.

        Return the information, prayer times and iqama times of a mosque for the whole
        year.

        Responses are cached for a long time: `times`, `shuruq` and the Jumu'a times
        describe the day the response was generated, so read the times of a given day
        from `calendar` and `iqama_calendar` instead.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The prayer times of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/2.0/mosque/{uuid}/prayer-times",
            path_params={"uuid": uuid},
            response_type=_PRAYER_TIMES,
        )

    def hijri_settings(self, uuid: str) -> HijriSettings:
        """Get Hijri date settings.

        Return how the Hijri date of a mosque is computed: the Kuwaiti algorithm on
        today's date shifted by `hijri_adjustment` days, with the day replaced by 30
        when `hijri_date_force_to_30` is `True`.

        These settings change around the start of the Hijri months, after the moon
        sighting, sometimes for every mosque of a country at once. Read them from this
        endpoint rather than from `client.mosques.prayer_times()`, whose copy can lag
        behind.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The Hijri date settings of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/hijri-date",
            path_params={"uuid": uuid},
            response_type=_HIJRI_SETTINGS,
        )

    def config(self, uuid: str) -> MosqueConfig:
        """Get the screen settings.

        Return the settings of the mosque screens: what they display, the adhan and
        iqama options, and whether the mosque displays Sabah and Imsak.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The screen settings of the mosque.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/config",
            path_params={"uuid": uuid},
            response_type=_CONFIG,
        )

    def flash_message(self, uuid: str) -> FlashMessage | None:
        """Get the flash message.

        Return the flash message of a mosque, or `None` when it has none.

        The message is returned before its `start_date` and after its `end_date` too:
        the mosque screens show it from `start_date` to `end_date` included, in the time
        zone of the mosque. The same message is in the `flash` of
        `client.mosques.prayer_times()`, a much larger response.

        Args:
            uuid: UUID of the mosque, as returned by `client.mosques.search()`.

        Returns:
            The flash message of the mosque, or `None`.

        Raises:
            AuthenticationError: Missing, invalid or disabled API token.
            PermissionDeniedError: The account has used all the API calls of its quota.
            NotFoundError: No published mosque has this UUID.
            APIError: The request failed in another way.
        """
        return self._client._request(
            "GET",
            "/3.0/mosque/{uuid}/flash-message",
            path_params={"uuid": uuid},
            response_type=_FLASH_MESSAGE,
        )
