# Generated by codegen/generate.py from mawaqit/api-spec v0.1.1. Do not edit.
"""The clients of the MAWAQIT API."""

from __future__ import annotations

from functools import cached_property

from ._base_client import AsyncAPIClient, SyncAPIClient
from .resources import AsyncAuth, AsyncMosques, Auth, Mosques

__all__ = ["AsyncMawaqitClient", "MawaqitClient"]


class AsyncMawaqitClient(AsyncAPIClient):
    """The async client of the MAWAQIT API.

    Example:
        ```python
        async with AsyncMawaqitClient(token="...") as client:
            mosques = await client.mosques.search(word="paris")
            prayer_times = await client.mosques.prayer_times(mosques[0].uuid)
        ```
    """

    @cached_property
    def auth(self) -> AsyncAuth:
        """Get an API token."""
        return AsyncAuth(self)

    @cached_property
    def mosques(self) -> AsyncMosques:
        """Search mosques and read their prayer times."""
        return AsyncMosques(self)


class MawaqitClient(SyncAPIClient):
    """The sync client of the MAWAQIT API.

    Example:
        ```python
        with MawaqitClient(token="...") as client:
            mosques = client.mosques.search(word="paris")
            prayer_times = client.mosques.prayer_times(mosques[0].uuid)
        ```
    """

    @cached_property
    def auth(self) -> Auth:
        """Get an API token."""
        return Auth(self)

    @cached_property
    def mosques(self) -> Mosques:
        """Search mosques and read their prayer times."""
        return Mosques(self)
