# Generated by codegen/generate.py from mawaqit/api-spec v0.5.1. Do not edit.
"""The models of the MAWAQIT API responses."""

from __future__ import annotations

from datetime import date, datetime

from pydantic import Field

from ._models import BaseModel

__all__ = [
    "Account",
    "Announcement",
    "FlashMessage",
    "Hadith",
    "HijriSettings",
    "Mosque",
    "MosqueConfig",
    "MosqueSummary",
    "PrayerTimes",
]


class Account(BaseModel):
    """A MAWAQIT account and its API access."""

    id: int
    """ID of the account."""

    api_access_token: str = Field(
        validation_alias="apiAccessToken",
        serialization_alias="apiAccessToken",
        repr=False,
    )
    """API token of the account, to send in the `Api-Access-Token` header."""

    api_quota: int | None = Field(
        validation_alias="apiQuota", serialization_alias="apiQuota"
    )
    """Number of API calls the account is allowed to make. `0` or `None` means
    unlimited.
    """

    api_call_number: int | None = Field(
        validation_alias="apiCallNumber", serialization_alias="apiCallNumber"
    )
    """Number of API calls the account has made."""


class Mosque(BaseModel):
    """A mosque found by a search."""

    uuid: str
    """UUID of the mosque, used by the other endpoints."""

    name: str
    """Name of the mosque."""

    label: str
    """Name to display for the mosque."""

    type: str
    """Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`.
    """

    slug: str | None
    """Identifier of the mosque in its MAWAQIT page URL."""

    latitude: float
    """Latitude of the mosque, in degrees."""

    longitude: float
    """Longitude of the mosque, in degrees."""

    localisation: str
    """Address of the mosque, in one line."""

    proximity: int | None = None
    """Distance from the position of the search, in meters. Only present in a search
    around a position.
    """

    association_name: str | None = Field(
        validation_alias="associationName", serialization_alias="associationName"
    )
    """Name of the association that runs the mosque."""

    phone: str | None
    """Phone number of the mosque."""

    email: str | None
    """Email address of the mosque."""

    site: str | None
    """Website of the mosque."""

    payment_website: str | None = Field(
        validation_alias="paymentWebsite", serialization_alias="paymentWebsite"
    )
    """Website to donate to the mosque."""

    image: str
    """URL of the picture of the mosque, or of a default picture when it has none."""

    closed: str | None
    """Why the mosque is closed: `ADMINISTRATIVE`, `MAINTENANCE`, `PERMANENT` or
    `OTHER`. `None` when it is open.
    """

    women_space: bool | None = Field(
        validation_alias="womenSpace", serialization_alias="womenSpace"
    )
    """Whether the mosque has a space for women. `None` when unknown."""

    janaza_prayer: bool | None = Field(
        validation_alias="janazaPrayer", serialization_alias="janazaPrayer"
    )
    """Whether the mosque holds funeral prayers. `None` when unknown."""

    aid_prayer: bool | None = Field(
        validation_alias="aidPrayer", serialization_alias="aidPrayer"
    )
    """Whether the mosque holds the Eid prayers. `None` when unknown."""

    children_courses: bool | None = Field(
        validation_alias="childrenCourses", serialization_alias="childrenCourses"
    )
    """Whether the mosque gives courses to children. `None` when unknown."""

    adult_courses: bool | None = Field(
        validation_alias="adultCourses", serialization_alias="adultCourses"
    )
    """Whether the mosque gives courses to adults. `None` when unknown."""

    ramadan_meal: bool | None = Field(
        validation_alias="ramadanMeal", serialization_alias="ramadanMeal"
    )
    """Whether the mosque serves iftar meals during Ramadan. `None` when unknown."""

    handicap_accessibility: bool | None = Field(
        validation_alias="handicapAccessibility",
        serialization_alias="handicapAccessibility",
    )
    """Whether the mosque is accessible to people with disabilities. `None` when
    unknown.
    """

    ablutions: bool | None
    """Whether the mosque has an ablution room. `None` when unknown."""

    parking: bool | None
    """Whether the mosque has a car park. `None` when unknown."""

    times: list[str] | None
    """Today's Fajr, Shuruq, Dhuhr, Asr, Maghrib and Isha times, as HH:MM in the time
    zone of the mosque. `None` when the mosque has no prayer times.
    """

    iqama: list[str] | None
    """Today's iqama of Fajr, Dhuhr, Asr, Maghrib and Isha, either as HH:MM or as `+N`,
    N minutes after the adhan. `None` when the mosque has no prayer times.
    """

    jumua: str | None
    """Time of the first Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_2: str | None = Field(validation_alias="jumua2", serialization_alias="jumua2")
    """Time of the second Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_3: str | None = Field(validation_alias="jumua3", serialization_alias="jumua3")
    """Time of the third Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_as_duhr: bool = Field(
        validation_alias="jumuaAsDuhr", serialization_alias="jumuaAsDuhr"
    )
    """Whether Jumu'a is prayed at the time of Dhuhr."""

    iqama_enabled: bool = Field(
        validation_alias="iqamaEnabled", serialization_alias="iqamaEnabled"
    )
    """Whether the mosque publishes iqama times."""


class MosqueSummary(BaseModel):
    """A mosque found by its ID."""

    id: int
    """ID of the mosque."""

    uuid: str
    """UUID of the mosque, used by the other endpoints."""

    name: str
    """Name of the mosque."""

    type: str
    """Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`.
    """

    localisation: str
    """Address of the mosque, in one line."""

    image: str
    """URL of the picture of the mosque, or of a default picture when it has none."""


class Announcement(BaseModel):
    """An announcement published by a mosque."""

    id: int
    """ID of the announcement."""

    uuid: str
    """UUID of the mosque."""

    title: str | None
    """Title of the announcement."""

    content: str | None
    """Text of the announcement."""

    image: str | None
    """URL of the image of the announcement."""

    video: str | None
    """URL of the embedded video of the announcement."""

    start_date: str | None = Field(
        validation_alias="startDate", serialization_alias="startDate"
    )
    """When the announcement starts, as `YYYY-MM-DD HH:MM` in the time zone of the
    mosque.
    """

    end_date: str | None = Field(
        validation_alias="endDate", serialization_alias="endDate"
    )
    """When the announcement ends, as `YYYY-MM-DD HH:MM` in the time zone of the mosque.
    """

    updated: str | None
    """When the announcement was last updated, as `YYYY-MM-DD HH:MM`."""

    duration: int
    """How long the announcement stays on the mosque screen, in seconds."""

    is_mobile: bool = Field(validation_alias="isMobile", serialization_alias="isMobile")
    """Whether the announcement is shown in the mobile app."""

    is_desktop: bool = Field(
        validation_alias="isDesktop", serialization_alias="isDesktop"
    )
    """Whether the announcement is shown on the mosque screens."""

    tv_orientation: str = Field(
        validation_alias="tvOrientation", serialization_alias="tvOrientation"
    )
    """Orientation of the announcement on the mosque screens: `LANDSCAPE` or `PORTRAIT`.
    """


class FlashMessage(BaseModel):
    """A short message scrolling at the bottom of the mosque screens.

    The screens show it from `start_date` to `end_date` included.
    """

    content: str | None
    """Text of the message, limited to 200 characters by the back office."""

    uuid: str
    """UUID of the mosque."""

    start_date: date | None = Field(
        validation_alias="startDate", serialization_alias="startDate"
    )
    """First day of the message."""

    end_date: date | None = Field(
        validation_alias="endDate", serialization_alias="endDate"
    )
    """Last day of the message."""

    expire: int | None = Field(deprecated="expire is deprecated. Use `end_date`.")
    """Last day of the message, as a Unix timestamp. Use `end_date`."""

    color: str
    """Background color of the message, as a CSS hex color."""

    orientation: str
    """Direction of the text: `ltr` or `rtl`."""


class PrayerTimes(BaseModel):
    """The information and prayer times of a mosque for the year."""

    id: int
    """Numeric ID of the mosque."""

    uuid: str
    """UUID of the mosque."""

    name: str
    """Name of the mosque, followed by its city if the mosque chose so."""

    label: str
    """Name to display for the mosque, same as `name`."""

    type: str
    """Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`.
    """

    partner: bool
    """Whether the mosque is a MAWAQIT partner."""

    url: str
    """URL of the MAWAQIT page of the mosque."""

    stream_url: str | None = Field(
        validation_alias="streamUrl", serialization_alias="streamUrl"
    )
    """URL of the live audio stream of the mosque."""

    localisation: str
    """Address of the mosque, in one line."""

    country_code: str = Field(
        validation_alias="countryCode", serialization_alias="countryCode"
    )
    """Country of the mosque, as an ISO 3166-1 alpha-2 code."""

    timezone: str
    """IANA time zone of the mosque. Every time of this response is in this time zone.
    """

    latitude: float
    """Latitude of the mosque, in degrees."""

    longitude: float
    """Longitude of the mosque, in degrees."""

    association: str | None
    """Name of the association that runs the mosque."""

    phone: str | None
    """Phone number of the mosque."""

    email: str | None
    """Email address of the mosque."""

    site: str | None
    """Website of the mosque."""

    payment_website: str | None = Field(
        validation_alias="paymentWebsite", serialization_alias="paymentWebsite"
    )
    """Website to donate to the mosque."""

    image: str | None
    """URL of the main picture of the mosque."""

    interior_picture: str | None = Field(
        validation_alias="interiorPicture", serialization_alias="interiorPicture"
    )
    """URL of a picture of the inside of the mosque."""

    exterior_picture: str | None = Field(
        validation_alias="exteriorPicture", serialization_alias="exteriorPicture"
    )
    """URL of a picture of the outside of the mosque."""

    logo: str | None
    """URL of the logo of the mosque."""

    other_info: str | None = Field(
        validation_alias="otherInfo", serialization_alias="otherInfo"
    )
    """Other information published by the mosque."""

    closed: str | None
    """Why the mosque is closed: `ADMINISTRATIVE`, `MAINTENANCE`, `PERMANENT` or
    `OTHER`. `None` when it is open.
    """

    women_space: bool | None = Field(
        validation_alias="womenSpace", serialization_alias="womenSpace"
    )
    """Whether the mosque has a space for women. `None` when unknown."""

    janaza_prayer: bool | None = Field(
        validation_alias="janazaPrayer", serialization_alias="janazaPrayer"
    )
    """Whether the mosque holds funeral prayers. `None` when unknown."""

    aid_prayer: bool | None = Field(
        validation_alias="aidPrayer", serialization_alias="aidPrayer"
    )
    """Whether the mosque holds the Eid prayers. `None` when unknown."""

    children_courses: bool | None = Field(
        validation_alias="childrenCourses", serialization_alias="childrenCourses"
    )
    """Whether the mosque gives courses to children. `None` when unknown."""

    adult_courses: bool | None = Field(
        validation_alias="adultCourses", serialization_alias="adultCourses"
    )
    """Whether the mosque gives courses to adults. `None` when unknown."""

    ramadan_meal: bool | None = Field(
        validation_alias="ramadanMeal", serialization_alias="ramadanMeal"
    )
    """Whether the mosque serves iftar meals during Ramadan. `None` when unknown."""

    handicap_accessibility: bool | None = Field(
        validation_alias="handicapAccessibility",
        serialization_alias="handicapAccessibility",
    )
    """Whether the mosque is accessible to people with disabilities. `None` when
    unknown.
    """

    ablutions: bool | None
    """Whether the mosque has an ablution room. `None` when unknown."""

    parking: bool | None
    """Whether the mosque has a car park. `None` when unknown."""

    announcements: list[Announcement]
    """The announcements of the mosque."""

    events: list[Announcement]
    """The announcements that have both a start and an end date."""

    flash: FlashMessage | None = None
    """A short message scrolling at the bottom of the mosque screens. Absent when the
    mosque has none.
    """

    calendar: list[dict[str, list[str]]]
    """Prayer times of the year, one item per month from January to December. Each month
    maps its days, from `"1"`, to the Fajr, Shuruq, Dhuhr, Asr, Maghrib and Isha times,
    as HH:MM. Mosques that display Imsak have 7 times a day: Imsak, Sabah (used as
    Fajr), Shuruq, Dhuhr, Asr, Maghrib and Isha. Times entered by hand by the mosque can
    be invalid.
    """

    iqama_calendar: list[dict[str, list[str]]] = Field(
        validation_alias="iqamaCalendar", serialization_alias="iqamaCalendar"
    )
    """Iqama times of the year, one item per month from January to December. Each month
    maps its days, from `"1"`, to the iqama of Fajr, Dhuhr, Asr, Maghrib and Isha,
    either as HH:MM or as `+N`, N minutes after the adhan.
    """

    times: list[str]
    """Fajr, Dhuhr, Asr, Maghrib and Isha times of the day the response was generated,
    as HH:MM. Prefer `calendar`.
    """

    shuruq: str
    """Shuruq time of the day the response was generated, as HH:MM. Prefer `calendar`.
    """

    jumua: str | None
    """Time of the first Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_2: str | None = Field(validation_alias="jumua2", serialization_alias="jumua2")
    """Time of the second Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_3: str | None = Field(validation_alias="jumua3", serialization_alias="jumua3")
    """Time of the third Jumu'a prayer, as HH:MM. `None` when there is none."""

    jumua_as_duhr: bool = Field(
        validation_alias="jumuaAsDuhr", serialization_alias="jumuaAsDuhr"
    )
    """Whether Jumu'a is prayed at the time of Dhuhr. `jumua` is then the Dhuhr time of
    the next Friday.
    """

    aid_prayer_time: str | None = Field(
        validation_alias="aidPrayerTime", serialization_alias="aidPrayerTime"
    )
    """Time of the first Eid prayer, as HH:MM."""

    aid_prayer_time_2: str | None = Field(
        validation_alias="aidPrayerTime2", serialization_alias="aidPrayerTime2"
    )
    """Time of the second Eid prayer, as HH:MM."""

    aid_prayer_time_3: str | None = Field(
        validation_alias="aidPrayerTime3", serialization_alias="aidPrayerTime3"
    )
    """Time of the third Eid prayer, as HH:MM."""

    imsak_nb_min_before_fajr: int | None = Field(
        validation_alias="imsakNbMinBeforeFajr",
        serialization_alias="imsakNbMinBeforeFajr",
    )
    """Number of minutes between Imsak and Fajr."""

    iqama_enabled: bool = Field(
        validation_alias="iqamaEnabled", serialization_alias="iqamaEnabled"
    )
    """Whether the mosque publishes iqama times."""

    hijri_adjustment: int = Field(
        validation_alias="hijriAdjustment", serialization_alias="hijriAdjustment"
    )
    """Number of days added to the date before computing the Hijri date. Prefer
    `client.mosques.hijri_settings()`.
    """

    hijri_date_force_to_30: bool = Field(
        validation_alias="hijriDateForceTo30", serialization_alias="hijriDateForceTo30"
    )
    """Whether the day of the Hijri date is replaced by 30. Prefer
    `client.mosques.hijri_settings()`.
    """


class HijriSettings(BaseModel):
    """How the Hijri date of a mosque is computed."""

    hijri_adjustment: int = Field(
        validation_alias="hijriAdjustment", serialization_alias="hijriAdjustment"
    )
    """Number of days added to today's date before computing the Hijri date, usually
    between -2 and 2.
    """

    hijri_date_force_to_30: bool = Field(
        validation_alias="hijriDateForceTo30", serialization_alias="hijriDateForceTo30"
    )
    """Whether the day of the Hijri date is replaced by 30, when a month lasts one more
    day than the Kuwaiti algorithm expects.
    """


class MosqueConfig(BaseModel):
    """The settings of the screens of a mosque."""

    show_city_in_title: bool = Field(
        validation_alias="showCityInTitle", serialization_alias="showCityInTitle"
    )
    """Whether the city is shown after the name of the mosque."""

    show_logo: bool = Field(validation_alias="showLogo", serialization_alias="showLogo")
    """Whether the logo of the mosque is shown."""

    show_prayer_times_on_message_screen: bool = Field(
        validation_alias="showPrayerTimesOnMessageScreen",
        serialization_alias="showPrayerTimesOnMessageScreen",
    )
    """Whether the prayer times are shown on the screen of the announcements."""

    jumua_dhikr_reminder_enabled: bool = Field(
        validation_alias="jumuaDhikrReminderEnabled",
        serialization_alias="jumuaDhikrReminderEnabled",
    )
    """Whether a hadith about the behavior during Jumu'a is shown during it."""

    jumua_black_screen_enabled: bool = Field(
        validation_alias="jumuaBlackScreenEnabled",
        serialization_alias="jumuaBlackScreenEnabled",
    )
    """Whether the screen turns black during Jumu'a."""

    jumua_timeout: int = Field(
        validation_alias="jumuaTimeout", serialization_alias="jumuaTimeout"
    )
    """Approximate duration of Jumu'a, sermon and prayer, in minutes."""

    dua_after_prayer_show_times: list[str] = Field(
        validation_alias="duaAfterPrayerShowTimes",
        serialization_alias="duaAfterPrayerShowTimes",
    )
    """Approximate duration of Fajr, Dhuhr, Asr, Maghrib and Isha, in minutes, as
    strings.
    """

    hijri_date_enabled: bool = Field(
        validation_alias="hijriDateEnabled", serialization_alias="hijriDateEnabled"
    )
    """Whether the Hijri date is shown."""

    hijri_date_force_to_30: bool = Field(
        validation_alias="hijriDateForceTo30", serialization_alias="hijriDateForceTo30"
    )
    """Whether the day of the Hijri date is replaced by 30. Prefer
    `client.mosques.hijri_settings()`.
    """

    dua_after_azan_enabled: bool = Field(
        validation_alias="duaAfterAzanEnabled",
        serialization_alias="duaAfterAzanEnabled",
    )
    """Whether the dua after the adhan is shown."""

    dua_after_prayer_enabled: bool = Field(
        validation_alias="duaAfterPrayerEnabled",
        serialization_alias="duaAfterPrayerEnabled",
    )
    """Whether the invocations after the prayer are shown."""

    adhan_voice: str | None = Field(
        validation_alias="adhanVoice", serialization_alias="adhanVoice"
    )
    """Adhan played by the screens, `None` for a beep."""

    adhan_enabled_by_prayer: list[str] = Field(
        validation_alias="adhanEnabledByPrayer",
        serialization_alias="adhanEnabledByPrayer",
    )
    """Whether the adhan is played at Fajr, Dhuhr, Asr, Maghrib and Isha, as `"1"` or
    `"0"`.
    """

    adhan_duration: int = Field(
        validation_alias="adhanDuration", serialization_alias="adhanDuration"
    )
    """Approximate duration of the adhan, in seconds."""

    custom_athan: str | None = Field(
        validation_alias="customAthan", serialization_alias="customAthan"
    )
    """URL of the adhan recorded by the mosque, if any."""

    custom_athan_duration: int | None = Field(
        validation_alias="customAthanDuration",
        serialization_alias="customAthanDuration",
    )
    """Duration of the adhan recorded by the mosque, in seconds."""

    iqama_bip: bool = Field(validation_alias="iqamaBip", serialization_alias="iqamaBip")
    """Whether a sound is played at the iqama."""

    iqama_bip_sound: str | None = Field(
        validation_alias="iqamaBipSound", serialization_alias="iqamaBipSound"
    )
    """Sound played at the iqama."""

    iqama_full_screen_countdown: bool = Field(
        validation_alias="iqamaFullScreenCountdown",
        serialization_alias="iqamaFullScreenCountdown",
    )
    """Whether the countdown to the iqama takes the whole screen."""

    iqama_display_time: int = Field(
        validation_alias="iqamaDisplayTime", serialization_alias="iqamaDisplayTime"
    )
    """How long the iqama signal is shown, in seconds."""

    iqama_enabled: bool = Field(
        validation_alias="iqamaEnabled", serialization_alias="iqamaEnabled"
    )
    """Whether the mosque publishes iqama times."""

    iqama_more_important: bool | None = Field(
        validation_alias="iqamaMoreImportant", serialization_alias="iqamaMoreImportant"
    )
    """Whether the iqama times are highlighted rather than the adhan times."""

    always_display_hh_mm_format: bool = Field(
        validation_alias="alwaysDisplayHhMmFormat",
        serialization_alias="alwaysDisplayHhMmFormat",
    )
    """Whether iqama times are always shown as HH:MM, rather than as minutes after the
    adhan.
    """

    black_screen_when_praying: bool = Field(
        validation_alias="blackScreenWhenPraying",
        serialization_alias="blackScreenWhenPraying",
    )
    """Whether the screen turns black during the prayers."""

    wake_for_fajr_time: int | None = Field(
        validation_alias="wakeForFajrTime", serialization_alias="wakeForFajrTime"
    )
    """Minutes before Fajr of a first adhan to wake up, `None` for none."""

    fajr_fixation_compared_to_shuruq: int | None = Field(
        validation_alias="fajrFixationComparedToShuruq",
        serialization_alias="fajrFixationComparedToShuruq",
    )
    """Fajr is set this many minutes before Shuruq, `None` when it is not."""

    random_hadith_enabled: bool = Field(
        validation_alias="randomHadithEnabled",
        serialization_alias="randomHadithEnabled",
    )
    """Whether a random hadith is shown every 5 minutes."""

    random_hadith_interval_disabling: str | None = Field(
        validation_alias="randomHadithIntervalDisabling",
        serialization_alias="randomHadithIntervalDisabling",
    )
    """Between which prayers the hadiths are not shown, like during lessons."""

    hadith_lang: str = Field(
        validation_alias="hadithLang", serialization_alias="hadithLang"
    )
    """Language of the hadiths, like `ar`."""

    temperature_enabled: bool = Field(
        validation_alias="temperatureEnabled", serialization_alias="temperatureEnabled"
    )
    """Whether the outside temperature is shown."""

    temperature_unit: str = Field(
        validation_alias="temperatureUnit", serialization_alias="temperatureUnit"
    )
    """Unit of the temperature: `C` or `F`."""

    time_display_format: str = Field(
        validation_alias="timeDisplayFormat", serialization_alias="timeDisplayFormat"
    )
    """Time format of the screens: `24` or `12`."""

    theme: str
    """Theme of the screens, like `mawaqit`."""

    background_type: str = Field(
        validation_alias="backgroundType", serialization_alias="backgroundType"
    )
    """Background of the screens: `motif` or `color`."""

    background_motif: str = Field(
        validation_alias="backgroundMotif", serialization_alias="backgroundMotif"
    )
    """ID of the background pattern."""

    background_color: str = Field(
        validation_alias="backgroundColor", serialization_alias="backgroundColor"
    )
    """Background color, as a CSS hex color."""

    background_url: str | None = Field(
        validation_alias="backgroundUrl", serialization_alias="backgroundUrl"
    )
    """URL of the background picture of the screens."""

    footer: bool
    """Whether the footer is shown."""

    display_qr_code_and_logo_on_android_tv: bool = Field(
        validation_alias="displayQrCodeAndLogoOnAndroidTV",
        serialization_alias="displayQrCodeAndLogoOnAndroidTV",
    )
    """Whether the MAWAQIT logo and QR code are shown on Android TV."""

    displaying_sabah_imsak: bool = Field(
        validation_alias="displayingSabahImsak",
        serialization_alias="displayingSabahImsak",
    )
    """Whether the mosque displays Sabah and Imsak. Its `calendar` then has 7 times a
    day, see `client.mosques.prayer_times()`.
    """

    sabah_imsak_start_date: datetime | None = Field(
        validation_alias="sabahImsakStartDate",
        serialization_alias="sabahImsakStartDate",
    )
    """From when Sabah and Imsak are displayed."""

    sabah_imsak_end_date: datetime | None = Field(
        validation_alias="sabahImsakEndDate", serialization_alias="sabahImsakEndDate"
    )
    """Until when Sabah and Imsak are displayed."""


class Hadith(BaseModel):
    """A hadith, as the mosque screens show it."""

    text: str
    """Text of the hadith, on one line, starting with a space. In every language, it
    keeps the Arabic honorifics after the names of the Prophet and his companions.
    """

    lang: str
    """Language of the text, like `fr`. For a pair, the one drawn."""
