"""v2 API namespace — reached via ``client.v2``.

Every method is a thin, typed wrapper: build the path/params, delegate to the
shared authenticated request, and parse the JSON into the generated model. This
module is the async source of truth; the sync version is generated by unasync.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import TypeAdapter

from .._generated import v2 as models
from .._transport import query_params

if TYPE_CHECKING:
    from .client import AsyncMawaqitClient

_MOSQUE_LIST = TypeAdapter(list[models.Mosque])
_UUID_LIST = TypeAdapter(list[str])


class MosqueResource:
    """Mosque endpoints of the v2 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def search(
        self,
        *,
        word: str | None = None,
        lat: float | None = None,
        lon: float | None = None,
        page: int | None = None,
        items_per_page: int | None = None,
        radius: float | None = None,
    ) -> list[models.Mosque]:
        """Search mosques by keyword, or by coordinates when ``lat``/``lon`` are set."""
        response = await self._client._request(
            "GET",
            "2.0/mosque/search",
            params=query_params(
                word=word,
                lat=lat,
                lon=lon,
                page=page,
                itemsPerPage=items_per_page,
                radius=radius,
            ),
        )
        return _MOSQUE_LIST.validate_python(response.json())

    async def list_uuid(self, *, page: int | None = None) -> list[str]:
        """List every mosque uuid (paginated)."""
        response = await self._client._request(
            "GET", "2.0/mosque/list-uuid", params=query_params(page=page)
        )
        return _UUID_LIST.validate_python(response.json())

    async def prayer_times(
        self,
        uuid: str,
        *,
        calendar: bool | None = None,
        updated_at: int | None = None,
    ) -> models.PrayerTimes:
        """Prayer times and mosque info; pass ``calendar`` for the full year."""
        response = await self._client._request(
            "GET",
            f"2.0/mosque/{uuid}/prayer-times",
            params=query_params(calendar=calendar, updatedAt=updated_at),
        )
        return models.PrayerTimes.model_validate(response.json())

    async def weather(self, uuid: str) -> models.Weather:
        """Weather for the mosque's city."""
        response = await self._client._request("GET", f"2.0/mosque/{uuid}/weather")
        return models.Weather.model_validate(response.json())

    async def data(self, mosque_id: str) -> dict[str, Any]:
        """Full offline-sync payload. The swagger types this as a bare object, so
        it is returned untyped (``dict``)."""
        response = await self._client._request("GET", f"2.0/mosque/{mosque_id}/data")
        data: dict[str, Any] = response.json()
        return data

    async def map(self, country_code: str) -> models.MosqueForMap:
        """Mosques shown on the homepage map for a country code (FR, DZ, ...)."""
        response = await self._client._request("GET", f"2.0/mosque/map/{country_code}")
        return models.MosqueForMap.model_validate(response.json())

    async def list(
        self, *, order: str | None = None, page: int | None = None
    ) -> list[models.Mosque]:
        """List all mosques (paginated)."""
        response = await self._client._request(
            "GET", "2.0/mosque", params=query_params(order=order, page=page)
        )
        return _MOSQUE_LIST.validate_python(response.json())


class HadithResource:
    """Hadith endpoints of the v2 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def random(
        self, *, lang: str | None = None, max_length: int | None = None
    ) -> models.Hadith:
        """A random hadith, optionally filtered by language and max length."""
        response = await self._client._request(
            "GET",
            "2.0/hadith/random",
            params=query_params(lang=lang, maxLength=max_length),
        )
        return models.Hadith.model_validate(response.json())


class StatisticResource:
    """Statistic endpoints of the v2 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def favorite(self, uuid: str) -> None:
        """Increment the mosque's subscriber counter."""
        await self._client._request("POST", f"2.0/statistic/mosque/{uuid}/favorite")

    async def unfavorite(self, uuid: str) -> None:
        """Decrement the mosque's subscriber counter."""
        await self._client._request("DELETE", f"2.0/statistic/mosque/{uuid}/favorite")


class SupportResource:
    """Support endpoint of the v2 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def get(self, *, country: str | None = None) -> models.Support:
        """WhatsApp support URLs, optionally for a specific country."""
        response = await self._client._request(
            "GET", "2.0/support", params=query_params(country=country)
        )
        return models.Support.model_validate(response.json())


class MeResource:
    """Authenticated-user endpoint of the v2 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def get(self) -> models.Me:
        """The authenticated user's id, token and API quota."""
        response = await self._client._request("GET", "2.0/me")
        return models.Me.model_validate(response.json())


class AsyncV2:
    """Namespace grouping every v2 resource under ``client.v2``."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self.mosque = MosqueResource(client)
        self.hadith = HadithResource(client)
        self.statistic = StatisticResource(client)
        self.support = SupportResource(client)
        self.me = MeResource(client)
