"""v3 API namespace — reached via ``client.v3``.

Same thin-wrapper design as :mod:`mawaqit._async.v2`. Async source of truth;
the sync version is generated by unasync.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import TypeAdapter

from .._generated import v3 as models
from .._transport import query_params
from ..responses import AnnouncementsAndEvents

if TYPE_CHECKING:
    from .client import AsyncMawaqitClient

_FLASH_MESSAGE_LIST = TypeAdapter(list[models.FlashMessage])


class MosqueResource:
    """Mosque endpoints of the v3 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def times(self, uuid: str) -> models.Times:
        """Prayer times, iqama and calendar for a mosque."""
        response = await self._client._request("GET", f"3.0/mosque/{uuid}/times")
        return models.Times.model_validate(response.json())

    async def info(self, uuid: str) -> models.Info:
        """Descriptive info for a mosque (address, services, flash message)."""
        response = await self._client._request("GET", f"3.0/mosque/{uuid}/info")
        return models.Info.model_validate(response.json())

    async def by_id(self, mosque_id: str) -> models.InfoById:
        """Minimal mosque info looked up by numeric id."""
        response = await self._client._request("GET", f"3.0/mosque/{mosque_id}")
        return models.InfoById.model_validate(response.json())

    async def by_slug(self, slug: str) -> models.InfoById:
        """Minimal mosque info looked up by slug."""
        response = await self._client._request("GET", f"3.0/mosque/slug/{slug}")
        return models.InfoById.model_validate(response.json())

    async def config(self, uuid: str) -> models.Config:
        """Big-screen display configuration for a mosque."""
        response = await self._client._request("GET", f"3.0/mosque/{uuid}/config")
        return models.Config.model_validate(response.json())

    async def announcements(self, uuid: str) -> AnnouncementsAndEvents:
        """Announcements and events for a mosque."""
        response = await self._client._request(
            "GET", f"3.0/mosque/{uuid}/announcements"
        )
        return AnnouncementsAndEvents.model_validate(response.json())

    async def flash_message(self, uuid: str) -> list[models.FlashMessage]:
        """Flash messages for a mosque."""
        response = await self._client._request(
            "GET", f"3.0/mosque/{uuid}/flash-message"
        )
        return _FLASH_MESSAGE_LIST.validate_python(response.json())

    async def hijri_date(self, uuid: str) -> models.HijriDate:
        """Hijri date adjustment parameters for a mosque."""
        response = await self._client._request("GET", f"3.0/mosque/{uuid}/hijri-date")
        return models.HijriDate.model_validate(response.json())

    async def messages(self, uuid: str) -> models.Messages:
        """Combined announcements/events message feed for a mosque."""
        response = await self._client._request("GET", f"3.0/mosque/{uuid}/messages")
        return models.Messages.model_validate(response.json())

    async def androidtv_life_status(
        self,
        uuid: str,
        *,
        device_id: str,
        brand: str | None = None,
        model: str | None = None,
        android_version: str | None = None,
        app_version: str | None = None,
    ) -> None:
        """Report an Android TV box life-status ping for a mosque."""
        body = query_params(
            **{
                "device-id": device_id,
                "brand": brand,
                "model": model,
                "android-version": android_version,
                "app-version": app_version,
            }
        )
        await self._client._request(
            "POST", f"3.0/mosque/{uuid}/androidtv-life-status", json=body
        )


class StatisticResource:
    """Statistic endpoints of the v3 API."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self._client = client

    async def installations(self) -> dict[str, Any]:
        """Number of installed mosques per country. The swagger schema for this
        endpoint is a bare object, so it is returned untyped (``dict``)."""
        response = await self._client._request("GET", "3.0/statistic/installations")
        data: dict[str, Any] = response.json()
        return data


class AsyncV3:
    """Namespace grouping every v3 resource under ``client.v3``."""

    def __init__(self, client: AsyncMawaqitClient) -> None:
        self.mosque = MosqueResource(client)
        self.statistic = StatisticResource(client)
